### ISSUE TITLE
uba安装成功后提示uba command not found

### ISSUE THREAD

**Issue by fsconline** [iuap-design/uba#13]
Administrator@chao MINGW64 ~
$ upm ls uba
bash: upm: command not found

Administrator@chao MINGW64 ~
$ npm ls uba
C:\Users\Administrator
`-- uba@1.4.5

Administrator@chao MINGW64 ~
$ uba --help
bash: uba: command not found

**Comment by kvkens** [comment]
请重新安装uba来解决不同操作系统下的编码问题`npm install uba -g`，我这边经过测试Mac OS以及Windows是可以安装全局命令来使用的，请检查相关权限。
