### ISSUE TITLE
uba 2.0.0 TODO LIST

### ISSUE THREAD

**Issue by kvkens** [iuap-design/uba#15]
----
# uba 2.0改版

序号 | 需求清单 | 说明 | 完成情况
---|---|---|---
1 | uba init操作优化 | 采用github api来访问uba-templates仓库数据用户键盘直观显示操作 | 已完成
2 | uba 核心功能拆分| 抽离出现无关的功能代码 | 已完成
3 | uba 命令拆分 | 后面拆分出`uba-core`,`uba-cli`,`uba-init`,`uba-server`等. | 待开发
4 | uba-templates | 仓库存放最佳实践的规范，有默认的最佳实践规范. | 已完成
5 | uba-templates  | 添加gulp+neoui+director.js 最佳实践| 已完成
6 | uba-templates  | 添加webpack+react+babel最佳实践 | 已完成
7 | uba-templates  | 添加webpack+tinper-bee组件 | 已完成

----

**Comment by kvkens** [comment]
# uba-templates

序号 | 名称 | 说明 | 完成情况
---|---|---|---
1 | kero + neoui |  第一套 | 完成
2 | kero + neoui |  第二套 | 完成
3 | react |  第三套 | 完成
4 | react |  第二套 | 完成
5 | react |  第一套 | 完成
6 | vue.js |  第三套 | 完成
7 | gulp + require.js |  第一套 | 完成

**Comment by GuoYongfeng** [comment]
个人理解，脚手架项目和最佳实践项目是不太一样的：

- 脚手架项目：**不包含业务含义**，更具有通用性，是对技术框架和工具的整合，是一种架构形态。
- 最佳实践项目：可以是对一个项目架构的抽象和总结，**包含业务含义**，对典型的业务处理给出了最好的实践方案，同时也具备对技术框架和工具的结合。

而 `uba` 可以初始化这两大类型的项目。
