### ISSUE TITLE
选择不自动安装npm包时提示信息不全且有问题

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/uba#18]
## 问题描述

执行初始化命令后，选择不自动安装npm包，出现以下信息：
```
? 是否自动安装npm依赖包 No
错误:取消自动安装npm依赖包，请手动执行npm install.
```

问题1：这不是错误，修改措辞
问题2：选择不自动安装，那么用户该怎么操作，`请手动执行npm install` 就这样提示？

## 期望

给出用户友好的提示方式。

**Comment by kvkens** [comment]
已经修改友好提示并发包到npm.
