### ISSUE TITLE
【Feature】多页应用的分包策略

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/uba#19]
需求：`multi-page` 工程中，多个页面 `entry` 引用了相同的 `js` 文件，能够提取出公共的 `chunk` 并形成公共的 `js` 文件，最后在 `html` 中加载。

场景：混合应用中，前端静态资源存储在客户端，前端资源体积过大会导致应用安装包过大。

**Comment by kvkens** [comment]
此问题资金云项目已经按照此方式做过优化，玩事APP目前采用更快的插件来做这事。也有私下测试过分包构建的策略。
