### ISSUE TITLE
使用uba server，ctrl + c 关闭任务时，有时会清不掉服务。

### ISSUE THREAD

**Issue by BoyuZhou** [iuap-design/uba#20]
使用uba server，ctrl + c 关闭任务时，有时会清不掉服务。再次启动会报端口冲突。

**Comment by kvkens** [comment]
这个在系统上一次是不行，一次ctrl+c是关闭当前shell，二次才是关闭完整的进程，我一般是多按几次才好。这不属于uba的问题，是计算机进程的普遍问题。
