### ISSUE TITLE
我执行完init后不知道干嘛

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/uba#21]
我执行完init后，我不知道应该做什么，文档不是很明确。是否可以把文档优化一下？傻瓜式安装？

**Comment by kvkens** [comment]
init完后下一步在使用uba的时候里面已经给出提示，注意观察哈！

文档这里有说明[文档](https://github.com/iuap-design/tinper-uba/blob/master/README_zh-CN.md#使用)

**Comment by HuYuee** [comment]
可以放个gif，哈哈😆
