### ISSUE TITLE
uba线上混淆代码有问题，不好调试

### ISSUE THREAD

**Issue by HuYuee** [iuap-design/uba#4]
uba在最终的混淆代码，build出包之后，让到线上，没法调试，是否应该在建立一个本地线上开发态

**Comment by kvkens** [comment]
为何不在开发中调试好了没问题在build呢？
理论上build是指我们项目最终没问题发布，本身初衷就是为了最简最优的原则去做的。

不过这个问题值得考虑。thx!

**Comment by kvkens** [comment]
@NeoEvanSun 协助解决.
