### ISSUE TITLE
文件夹更改位置，uba的server就跑不起来了

### ISSUE THREAD

**Issue by HuYuee** [iuap-design/uba#8]
用uba工具生成的项目文件夹，在开发完成自己想要的功能之后将其整个拷贝到别的目录下，然后在项目文件夹下是执行uba servre一直报错，说module找不到

**Comment by songhlc** [comment]
@HuyueHappy 遇到问题请贴出详细的日志 拷到其他目录下先运行npm install安装一下模块依赖
